# https://gleam.run/writing-gleam/gleam-toml/.

name = "backend"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.32.0 and < 1.0.0"
gleam_http = ">= 3.7.1 and < 4.0.0"
mist = ">= 3.0.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
