name: main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  CI_NIX_STORE: ~/nix
  CI_NIX_FLAKE: .#default
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nix
        uses: nixbuild/nix-quick-install-action@v29
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Nix
        uses: actions/cache@v4
        with:
          path: ${{ env.CI_NIX_STORE }}
          key: ${{ runner.os }}-nix-${{ hashFiles('flake.nix', 'flake.lock') }}
      - name: Lint
        run: |
          nix --store ${{ env.CI_NIX_STORE }} \
            develop ${{ env.CI_NIX_FLAKE }} --command \
            editorconfig-checker && echo "ok"
